name: 自动同步河南优选IP

on:
  schedule:
    # 第一条规则：在第 0、3、6、9、12、15、18、21 小时的第 0 分钟运行
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
    # 第二条规则：在第 1、4..等小时的第 30 分钟运行。两相结合，刚好每 90 分钟运行一次！
    - cron: '30 1,4,7,10,13,16,19,22 * * *'
  workflow_dispatch:
    # 允许你在 Actions 页面上手动点击按钮随时触发运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 赋予脚本把新生成的 txt 写入仓库的权限

    steps:
    - name: 检查仓库代码
      uses: actions/checkout@v3

    - name: 安装 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装运行依赖
      run: pip install requests

    - name: 运行定制抓取脚本
      run: python get_ip.py

    - name: 自动将新生成的优选文本推送到仓库
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add my_best_bj.txt
        git commit -m "自动更新河南联通电信优选IP" || exit 0
        git push
